name: "Travel Time"
description: "My first real add-on!"
version: "1.0.0"
slug: "travel_time"
init: false
startup: application
boot: manual
host_network: true
ports:
  6730/tcp: 6730
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
