name: "Travel Time"
description: "Unlimited travel-time lookups via Google Maps — no registration, credit card, or API key required."
version: "1.0.0"
slug: "googlemapstraveltime"
init: false
startup: application
boot: manual
ports:
  8000/tcp: 8000
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
